version: "3.6"
services:
  preprocessors:
    build:
      context: models_api
      dockerfile: Dockerfile
    expose:
      - "8000"
    env_file:
      - models_api/.env
    ports:
       - "8000:8000"
