version: "3.6"
services:
  tg_bot:
    container_name: tg_bot
    build:
      context: tg_bot/
    env_file: tg_bot/.env

  postgres:
    container_name: postgres_context
    image: postgres
    env_file:
      - .env
    environment:
      PGDATA: /data/postgres
    volumes:
      - ./postgres:/data/postgres
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"

volumes:
  postgres:

